### ISSUE TITLE
cabal: can't find source for Data/Glome/Box

### ISSUE THREAD

**Issue by yihuang** [jimsnow/glome#1]
Build GlomeTrace failed, looks like missing source files.

**Comment by jimsnow** [comment]
Looks like I missed that file when I did the initial commit.  It should work now.  (Let me know if it doesn't.)  Thanks for letting me know.

**Comment by yihuang** [comment]
Now, source for "Data/Glome/Cone" is not found.

**Comment by jimsnow** [comment]
Sorry about that.  Cone.hs is in there now.
